// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUtAFD03m_DGNZdpYgFQD99dza_qjhzk',
    appId: '1:1028864422854:web:d4c0afd9ba19ab3839f8c7',
    messagingSenderId: '1028864422854',
    projectId: 'storeapp-40c0a',
    authDomain: 'storeapp-40c0a.firebaseapp.com',
    storageBucket: 'storeapp-40c0a.firebasestorage.app',
    measurementId: 'G-SJRKHJ63W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FwFOxM9_GK12htaRfl11CAjmQ_FS_Wo',
    appId: '1:1028864422854:android:e83927b080cc0d0439f8c7',
    messagingSenderId: '1028864422854',
    projectId: 'storeapp-40c0a',
    storageBucket: 'storeapp-40c0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2LJ7CwD7Ovat1xiJIEv6McaHzTGZKGok',
    appId: '1:1028864422854:ios:fdf3a23c9a84f0f939f8c7',
    messagingSenderId: '1028864422854',
    projectId: 'storeapp-40c0a',
    storageBucket: 'storeapp-40c0a.firebasestorage.app',
    iosClientId: '1028864422854-rvfdm823v9hqtmo1obp0ofm65gsjltnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2LJ7CwD7Ovat1xiJIEv6McaHzTGZKGok',
    appId: '1:1028864422854:ios:fdf3a23c9a84f0f939f8c7',
    messagingSenderId: '1028864422854',
    projectId: 'storeapp-40c0a',
    storageBucket: 'storeapp-40c0a.firebasestorage.app',
    iosClientId: '1028864422854-rvfdm823v9hqtmo1obp0ofm65gsjltnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDUtAFD03m_DGNZdpYgFQD99dza_qjhzk',
    appId: '1:1028864422854:web:4c8752aaa497b3ca39f8c7',
    messagingSenderId: '1028864422854',
    projectId: 'storeapp-40c0a',
    authDomain: 'storeapp-40c0a.firebaseapp.com',
    storageBucket: 'storeapp-40c0a.firebasestorage.app',
    measurementId: 'G-X3M2FPYZ75',
  );
}
