name: Flutter CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project (fail on errors only)
        run: |
          flutter analyze > analyze_output.txt
          cat analyze_output.txt
          if grep -q "error •" analyze_output.txt; then
            echo "❌ Flutter analyze found errors"
            exit 1
          else
            echo "✅ No errors found. Continuing..."
          fi

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
